language: cpp

compiler:
  - gcc
  - clang

env:
  - AUTOTOOLS=no BUILD=shared
  - AUTOTOOLS=no BUILD=static

before_install:
  - gem install sass
  - git clone https://github.com/mgreter/libsass.git -b api/c-interface
  - cd libsass && git submodule init && git submodule update && cd ..
  - export SASS_LIBSASS_PATH=libsass

script:
  - make test
