#!/bin/sh

set -e

if [ -z "$SASS_LIBSASS_PATH" ]; then
  export SASS_LIBSASS_PATH="$( dirname $0 )"/../../libsass/
  echo "SASS_LIBSASS_PATH env-variable missing"
  echo "Using default: $SASS_LIBSASS_PATH"
fi

if [ ! -d "$SASS_LIBSASS_PATH" ]; then
  git clone https://github.com/sass/libsass.git "$SASS_LIBSASS_PATH"
else
  echo "LibSass source directory exists, skiping Git Clone"
fi

if [ -z "$SASS_SPEC_PATH" ]; then
  export SASS_SPEC_PATH="$( dirname $0 )"/../../sass-spec/
  echo "SASS_SPEC_PATH env-variable missing"
  echo "Using default: $SASS_SPEC_PATH"
fi

if [ ! -d "$SASS_SPEC_PATH" ]; then
  git clone https://github.com/sass/sass-spec.git "$SASS_SPEC_PATH"
else
    echo "Sass-spec test directory exists, skiping Git Clone"
fi
